import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, Mail, Copy, Check, Sparkles } from 'lucide-react';
import type { AdvisorInsight } from '@/lib/api';
import { EmptyAnalysisIcon } from '@/components/ui/CustomIcons';

interface AIInsightPanelProps {
  insight: AdvisorInsight | null;
  isLoading: boolean;
}

export function AIInsightPanel({ insight, isLoading }: AIInsightPanelProps) {
  const [activeTab, setActiveTab] = useState<'playbook' | 'sentiment' | 'email'>('playbook');
  const [copied, setCopied] = useState(false);

  // Reset tab when insight changes
  useEffect(() => {
    if (insight) {
      setActiveTab('playbook');
    }
  }, [insight]);

  const handleCopy = async () => {
    if (insight?.email_draft) {
      await navigator.clipboard.writeText(insight.email_draft);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const tabs = [
    { id: 'playbook', label: 'Strategic Playbook', icon: Check },
    { id: 'sentiment', label: 'Sentiment Analysis', icon: Sparkles },
    { id: 'email', label: 'Email Draft', icon: Mail },
  ] as const;

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="p-0 h-full flex flex-col bg-white"
    >
      {/* Header - Always Visible */}
      <div className="flex items-center gap-3 mb-0 p-6 border-b-2 border-black bg-white shrink-0">
        <div className="w-10 h-10 border-2 border-black bg-black text-white flex items-center justify-center shadow-[4px_4px_0px_0px_rgba(0,0,0,0.2)]">
          <Sparkles className="w-5 h-5" />
        </div>
        <div>
          <h3 className="text-lg font-bold text-black uppercase tracking-tight">Strategic Analysis</h3>
          <p className="text-[10px] text-gray-500 uppercase tracking-widest font-bold">Generated by RevIQ Intelligence</p>
        </div>
      </div>

      {/* Tabs - Always Visible */}
      <div className="flex items-center shrink-0 border-b-2 border-black bg-gray-100">
        {tabs.map((tab) => {
          const isActive = activeTab === tab.id;
          const Icon = tab.icon;
          const isDisabled = !insight && !isLoading;

          return (
            <button
              key={tab.id}
              onClick={() => !isDisabled && setActiveTab(tab.id)}
              disabled={isDisabled}
              className={`
                flex-1 flex items-center justify-center gap-2 py-4 text-xs font-bold uppercase tracking-wider transition-all duration-200 border-r-2 border-black last:border-r-0
                ${isActive && !isDisabled
                  ? 'bg-black text-white'
                  : isDisabled
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                    : 'bg-white text-black hover:bg-gray-200'
                }
              `}
            >
              <Icon className="w-3.5 h-3.5" />
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar min-h-0 relative bg-gray-50/50">
        <AnimatePresence mode="wait">
          {isLoading ? (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-4 absolute inset-0 bg-white/90 backdrop-blur-sm z-10 flex flex-col items-center justify-center"
            >
              <div className="flex items-center gap-3">
                <div className="w-4 h-4 border-2 border-black bg-black animate-spin" />
                <span className="text-sm font-bold uppercase tracking-wider text-black">Analyzing account data...</span>
              </div>
            </motion.div>
          ) : !insight ? (
            <motion.div
              key="empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="h-full flex items-center justify-center"
            >
              <div className="text-center opacity-100 border-2 border-black bg-white p-8 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
                <EmptyAnalysisIcon className="w-24 h-24 mx-auto mb-4 grayscale opacity-100" />
                <p className="text-black font-bold uppercase tracking-wider text-xs">Select an account and generate analysis.</p>
              </div>
            </motion.div>
          ) : (
            <div className="h-full flex flex-col">
              {/* Notification Alert - Persistent if present */}
              {activeTab === 'playbook' && insight.notification && (
                <div className="mb-6 p-4 bg-red-50 border-2 border-black shadow-[4px_4px_0px_0px_rgba(239,68,68,1)] shrink-0">
                  <div className="flex items-start gap-3">
                    <AlertTriangle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-sm text-black font-medium leading-relaxed">
                        {insight.notification}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Tab Content */}
              <AnimatePresence mode="wait">
                {activeTab === 'playbook' && insight.playbook && (
                  <motion.div
                    key="playbook"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                    className="space-y-4"
                  >
                    <div className="p-6 border-2 border-black bg-indigo-50/30 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                      <div className="flex items-center gap-3 mb-4 border-b-2 border-black pb-3">
                        <div className="p-1.5 border-2 border-black bg-indigo-600 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                          <Check className="w-4 h-4 text-white" />
                        </div>
                        <h4 className="font-black text-black text-sm uppercase tracking-wider">Recommended Strategy</h4>
                      </div>
                      <div className="space-y-4">
                        <div>
                          <p className="text-xs font-black text-indigo-700 uppercase tracking-widest mb-4 bg-white inline-block px-2 py-1 border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,0.5)]">{insight.playbook.strategy_name}</p>
                          <ul className="space-y-3">
                            {insight.playbook.action_steps.map((step, idx) => (
                              <li key={idx} className="flex items-start gap-3 text-sm text-black bg-white p-3 border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,0.1)] hover:shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[-1px] hover:translate-y-[-1px] transition-all">
                                <span className="w-6 h-6 border-2 border-black bg-black text-white flex items-center justify-center text-[10px] font-black shrink-0 mt-0.5 shadow-[1px_1px_0px_0px_rgba(0,0,0,0.5)]">
                                  {idx + 1}
                                </span>
                                <span className="font-medium leading-relaxed">{step}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div className="pt-4 border-t-2 border-black/10">
                          <div className="bg-yellow-50 border-2 border-black p-3 flex gap-2 items-start">
                            <Sparkles className="w-4 h-4 text-black mt-0.5 shrink-0" />
                            <p className="text-xs text-black leading-relaxed">
                              <span className="font-black uppercase tracking-wide">Expected Outcome:</span> {insight.playbook.expected_outcome}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}

                {activeTab === 'sentiment' && insight.sentiment_analysis && (
                  <motion.div
                    key="sentiment"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                    className="space-y-4"
                  >
                    <div className="p-6 border-2 border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                      <div className="flex items-center justify-between mb-6 border-b-2 border-black pb-4">
                        <div className="flex items-center gap-3">
                          <div className="p-1.5 border-2 border-black bg-pink-500 shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                            <Sparkles className="w-4 h-4 text-white" />
                          </div>
                          <h4 className="font-black text-black text-sm uppercase tracking-wider">Sentiment Analysis</h4>
                        </div>
                        <div className={`px-4 py-1.5 text-xs font-black border-2 border-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] uppercase tracking-wide ${insight.sentiment_analysis.sentiment_score > 0
                          ? 'bg-green-100 text-green-700'
                          : insight.sentiment_analysis.sentiment_score < 0
                            ? 'bg-red-100 text-red-600'
                            : 'bg-gray-100 text-gray-700'
                          }`}>
                          {insight.sentiment_analysis.overall_sentiment}
                        </div>
                      </div>

                      <div className="space-y-6">
                        <div>
                          <h5 className="text-xs font-black text-black uppercase tracking-widest mb-3 flex items-center gap-2">
                            <span className="w-2 h-2 bg-black"></span> Key Themes Detected
                          </h5>
                          <div className="flex flex-wrap gap-3">
                            {insight.sentiment_analysis.key_themes.map((theme, i) => (
                              <span key={i} className="text-xs px-3 py-1.5 bg-white text-black border-2 border-black font-bold shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:translate-y-[-1px] hover:shadow-[3px_3px_0px_0px_rgba(0,0,0,1)] transition-all cursor-default">
                                {theme}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}

                {activeTab === 'email' && insight.email_draft && (
                  <motion.div
                    key="email"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                    className="space-y-4 h-full"
                  >
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-black text-black uppercase tracking-wider">Generated Draft</span>
                      <motion.button
                        onClick={handleCopy}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        className="flex items-center gap-1.5 px-4 py-2 border-2 border-black bg-white text-black text-xs font-bold uppercase tracking-wider shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:bg-black hover:text-white transition-colors"
                      >
                        {copied ? (
                          <>
                            <Check size={14} />
                            Copied!
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            Copy
                          </>
                        )}
                      </motion.button>
                    </div>
                    <div className="p-6 border-2 border-black bg-white h-full overflow-auto shadow-[4px_4px_0px_0px_rgba(0,0,0,0.1)]">
                      <pre className="text-sm text-black whitespace-pre-wrap font-mono leading-relaxed">
                        {insight.email_draft}
                      </pre>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}
        </AnimatePresence>
      </div>
    </motion.div>
  );
}
